/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.SingleSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Julio López
 */
public class VistaMecanico1 extends javax.swing.JFrame {

    /**
     * Creates new form JefeTaller
     */
 
      
    public VistaMecanico1() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panelLogo = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        BtnModoOscuro = new javax.swing.JToggleButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelInforme = new javax.swing.JPanel();
        panel2D = new javax.swing.JPanel();
        panelCOrona = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        panelSuspencion = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        panelDireccion = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        panelTrnas = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        panelMotor = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jcomboDireccion = new javax.swing.JComboBox<>();
        jComboSuspencion = new javax.swing.JComboBox<>();
        jComboTransmision = new javax.swing.JComboBox<>();
        jcomboCorona = new javax.swing.JComboBox<>();
        jComboMotor = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        bntSuspencion = new javax.swing.JToggleButton();
        btnDireccion = new javax.swing.JToggleButton();
        btnTransmision = new javax.swing.JToggleButton();
        btnCorona = new javax.swing.JToggleButton();
        btnMotor = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboEstado = new javax.swing.JComboBox<>();
        btnEnviarInforme = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextComentario = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jSpinnerHoras = new javax.swing.JSpinner();
        jSeparator1 = new javax.swing.JSeparator();
        jComboIdBus = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        PanelTabla = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaInforme = new javax.swing.JTable();
        btnListarinforme = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        panelUsuario = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        jPanelBtns = new javax.swing.JPanel();
        JpaneRepor = new javax.swing.JPanel();
        JlabRepor = new javax.swing.JLabel();
        panelBtnInforme = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelLogo.setBackground(new java.awt.Color(143, 207, 254));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/logo2.png"))); // NOI18N

        BtnModoOscuro.setBackground(new java.awt.Color(143, 207, 254));
        BtnModoOscuro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/modonoche1.png"))); // NOI18N
        BtnModoOscuro.setBorderPainted(false);
        BtnModoOscuro.setContentAreaFilled(false);

        javax.swing.GroupLayout panelLogoLayout = new javax.swing.GroupLayout(panelLogo);
        panelLogo.setLayout(panelLogoLayout);
        panelLogoLayout.setHorizontalGroup(
            panelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLogoLayout.createSequentialGroup()
                .addContainerGap(404, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(353, 353, 353)
                .addComponent(BtnModoOscuro)
                .addGap(22, 22, 22))
        );
        panelLogoLayout.setVerticalGroup(
            panelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
            .addGroup(panelLogoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(BtnModoOscuro)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(panelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 1140, 90));

        panelInforme.setBackground(new java.awt.Color(255, 255, 255));

        panel2D.setBackground(new java.awt.Color(255, 255, 255));
        panel2D.setLayout(null);

        panelCOrona.setBackground(new java.awt.Color(255, 255, 255));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/d.png"))); // NOI18N

        javax.swing.GroupLayout panelCOronaLayout = new javax.swing.GroupLayout(panelCOrona);
        panelCOrona.setLayout(panelCOronaLayout);
        panelCOronaLayout.setHorizontalGroup(
            panelCOronaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCOronaLayout.createSequentialGroup()
                .addComponent(jLabel16)
                .addGap(0, 2, Short.MAX_VALUE))
        );
        panelCOronaLayout.setVerticalGroup(
            panelCOronaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCOronaLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(22, 22, 22))
        );

        panel2D.add(panelCOrona);
        panelCOrona.setBounds(480, 40, 90, 200);

        panelSuspencion.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/b.png"))); // NOI18N

        javax.swing.GroupLayout panelSuspencionLayout = new javax.swing.GroupLayout(panelSuspencion);
        panelSuspencion.setLayout(panelSuspencionLayout);
        panelSuspencionLayout.setHorizontalGroup(
            panelSuspencionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSuspencionLayout.createSequentialGroup()
                .addComponent(jLabel10)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        panelSuspencionLayout.setVerticalGroup(
            panelSuspencionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSuspencionLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel10)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        panel2D.add(panelSuspencion);
        panelSuspencion.setBounds(230, 40, 130, 200);

        panelDireccion.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/a.png"))); // NOI18N
        jLabel8.setText("d");

        javax.swing.GroupLayout panelDireccionLayout = new javax.swing.GroupLayout(panelDireccion);
        panelDireccion.setLayout(panelDireccionLayout);
        panelDireccionLayout.setHorizontalGroup(
            panelDireccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDireccionLayout.createSequentialGroup()
                .addGap(0, 16, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelDireccionLayout.setVerticalGroup(
            panelDireccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDireccionLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(14, 14, 14))
        );

        panel2D.add(panelDireccion);
        panelDireccion.setBounds(60, 40, 170, 200);

        panelTrnas.setBackground(new java.awt.Color(255, 255, 255));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/c.png"))); // NOI18N

        javax.swing.GroupLayout panelTrnasLayout = new javax.swing.GroupLayout(panelTrnas);
        panelTrnas.setLayout(panelTrnasLayout);
        panelTrnasLayout.setHorizontalGroup(
            panelTrnasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTrnasLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel15))
        );
        panelTrnasLayout.setVerticalGroup(
            panelTrnasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTrnasLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panel2D.add(panelTrnas);
        panelTrnas.setBounds(360, 40, 120, 200);

        jPanel11.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panel2D.add(jPanel11);
        jPanel11.setBounds(500, 40, 40, 200);

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        panel2D.add(jSeparator2);
        jSeparator2.setBounds(60, 280, 730, 20);

        panelMotor.setBackground(new java.awt.Color(255, 255, 255));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/e.png"))); // NOI18N

        javax.swing.GroupLayout panelMotorLayout = new javax.swing.GroupLayout(panelMotor);
        panelMotor.setLayout(panelMotorLayout);
        panelMotorLayout.setHorizontalGroup(
            panelMotorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMotorLayout.createSequentialGroup()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 7, Short.MAX_VALUE))
        );
        panelMotorLayout.setVerticalGroup(
            panelMotorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMotorLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        panel2D.add(panelMotor);
        panelMotor.setBounds(570, 40, 230, 200);

        jcomboDireccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Tablero de kilometraje", "Barras de direccion", "Crucetas", "Barra estabilizadora", "Bolsa de aire", "Valvula de aire", "", "" }));
        jcomboDireccion.setBorder(null);
        jcomboDireccion.setEnabled(false);
        panel2D.add(jcomboDireccion);
        jcomboDireccion.setBounds(60, 290, 170, 30);

        jComboSuspencion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Valvula de aire", "Bolsa de aire", "Amortiguador", "Muelle", "Barra estabilizadora", "", "Ruedas delanteras" }));
        jComboSuspencion.setEnabled(false);
        panel2D.add(jComboSuspencion);
        jComboSuspencion.setBounds(240, 290, 120, 30);

        jComboTransmision.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Caja de transmision", " ", "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboTransmision.setEnabled(false);
        panel2D.add(jComboTransmision);
        jComboTransmision.setBounds(362, 290, 120, 30);

        jcomboCorona.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcomboCorona.setEnabled(false);
        panel2D.add(jcomboCorona);
        jcomboCorona.setBounds(492, 290, 100, 30);

        jComboMotor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboMotor.setEnabled(false);
        panel2D.add(jComboMotor);
        jComboMotor.setBounds(602, 290, 180, 30);

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setText("Indique lugar donde se hizo el mantenimiento");
        panel2D.add(jLabel18);
        jLabel18.setBounds(270, 10, 320, 20);

        bntSuspencion.setText("Suspencion");
        bntSuspencion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bntSuspencion.setBorderPainted(false);
        bntSuspencion.setContentAreaFilled(false);
        panel2D.add(bntSuspencion);
        bntSuspencion.setBounds(250, 260, 100, 20);

        btnDireccion.setText("Direccion");
        btnDireccion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDireccion.setBorderPainted(false);
        btnDireccion.setContentAreaFilled(false);
        panel2D.add(btnDireccion);
        btnDireccion.setBounds(100, 260, 90, 20);

        btnTransmision.setText("Transmision");
        btnTransmision.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTransmision.setBorderPainted(false);
        btnTransmision.setContentAreaFilled(false);
        panel2D.add(btnTransmision);
        btnTransmision.setBounds(370, 260, 100, 20);

        btnCorona.setText("Corona");
        btnCorona.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCorona.setBorderPainted(false);
        btnCorona.setContentAreaFilled(false);
        panel2D.add(btnCorona);
        btnCorona.setBounds(490, 260, 100, 20);

        btnMotor.setText("Motor");
        btnMotor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMotor.setBorderPainted(false);
        btnMotor.setContentAreaFilled(false);
        panel2D.add(btnMotor);
        btnMotor.setBounds(640, 260, 100, 20);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("COMPLETE TODOS LOS CAMPOS");

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel2.setText("Estado:");

        jComboEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Operativo", "Inoperativo" }));

        btnEnviarInforme.setText("Enviar Informe");
        btnEnviarInforme.setContentAreaFilled(false);
        btnEnviarInforme.setDefaultCapable(false);
        btnEnviarInforme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarInformeActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel7.setText("Comentario:");

        jTextComentario.setColumns(20);
        jTextComentario.setRows(5);
        jScrollPane1.setViewportView(jTextComentario);

        jLabel3.setText("Tiempo de Inactividad en Horas");

        jLabel9.setText("IdBus:");

        javax.swing.GroupLayout panelInformeLayout = new javax.swing.GroupLayout(panelInforme);
        panelInforme.setLayout(panelInformeLayout);
        panelInformeLayout.setHorizontalGroup(
            panelInformeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInformeLayout.createSequentialGroup()
                .addGroup(panelInformeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInformeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelInformeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelInformeLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboIdBus, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelInformeLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelInformeLayout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jSpinnerHoras))
                            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGroup(panelInformeLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel7))
                        .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelInformeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnEnviarInforme, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel2D, javax.swing.GroupLayout.DEFAULT_SIZE, 798, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );
        panelInformeLayout.setVerticalGroup(
            panelInformeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInformeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInformeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInformeLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addGroup(panelInformeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jSpinnerHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelInformeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jComboIdBus, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelInformeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jComboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEnviarInforme)
                        .addContainerGap(33, Short.MAX_VALUE))
                    .addComponent(panel2D, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Reporte", panelInforme);

        PanelTabla.setBackground(new java.awt.Color(255, 255, 255));

        tablaInforme.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "MecanicoID", "PeridoInforme", "BusID", "Fecha", "Descripcion", "NumeroSanja"
            }
        ));
        tablaInforme.setEnabled(false);
        jScrollPane2.setViewportView(tablaInforme);
        if (tablaInforme.getColumnModel().getColumnCount() > 0) {
            tablaInforme.getColumnModel().getColumn(0).setMaxWidth(30);
            tablaInforme.getColumnModel().getColumn(1).setMaxWidth(70);
            tablaInforme.getColumnModel().getColumn(2).setMaxWidth(100);
            tablaInforme.getColumnModel().getColumn(3).setMaxWidth(40);
            tablaInforme.getColumnModel().getColumn(4).setMaxWidth(80);
            tablaInforme.getColumnModel().getColumn(5).setMaxWidth(800);
            tablaInforme.getColumnModel().getColumn(6).setMaxWidth(110);
        }

        btnListarinforme.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Listar1.png"))); // NOI18N
        btnListarinforme.setText("Listar");
        btnListarinforme.setContentAreaFilled(false);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("@LISTA DE TAREAS ASIGNADAS A LOS MECANICOS");

        javax.swing.GroupLayout PanelTablaLayout = new javax.swing.GroupLayout(PanelTabla);
        PanelTabla.setLayout(PanelTablaLayout);
        PanelTablaLayout.setHorizontalGroup(
            PanelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTablaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelTablaLayout.createSequentialGroup()
                        .addComponent(btnListarinforme)
                        .addGap(714, 714, 714)
                        .addComponent(jLabel4))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        PanelTablaLayout.setVerticalGroup(
            PanelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTablaLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PanelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnListarinforme)
                    .addComponent(jLabel4))
                .addGap(15, 15, 15))
        );

        jTabbedPane1.addTab("Tareas", PanelTabla);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 94, 1140, 500));

        panelUsuario.setBackground(new java.awt.Color(143, 207, 254));
        panelUsuario.setLayout(null);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/PerfilMecanico.png"))); // NOI18N
        jLabel11.setText("jLabel11");
        panelUsuario.add(jLabel11);
        jLabel11.setBounds(10, 0, 200, 220);

        labelNombre.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        labelNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNombre.setText("MECANICO");
        panelUsuario.add(labelNombre);
        labelNombre.setBounds(10, 210, 190, 18);

        getContentPane().add(panelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 240));

        jPanelBtns.setBackground(new java.awt.Color(143, 207, 254));

        JpaneRepor.setBackground(new java.awt.Color(14, 172, 209));
        JpaneRepor.setName(""); // NOI18N
        JpaneRepor.setPreferredSize(new java.awt.Dimension(200, 40));

        JlabRepor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        JlabRepor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JlabRepor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/mantenimiento.png"))); // NOI18N
        JlabRepor.setText("TAREAS");
        JlabRepor.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                JlabReporMouseMoved(evt);
            }
        });
        JlabRepor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JlabReporMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JlabReporMouseExited(evt);
            }
        });

        javax.swing.GroupLayout JpaneReporLayout = new javax.swing.GroupLayout(JpaneRepor);
        JpaneRepor.setLayout(JpaneReporLayout);
        JpaneReporLayout.setHorizontalGroup(
            JpaneReporLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpaneReporLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JlabRepor, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );
        JpaneReporLayout.setVerticalGroup(
            JpaneReporLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JlabRepor)
        );

        panelBtnInforme.setBackground(new java.awt.Color(14, 172, 209));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/mantenimiento.png"))); // NOI18N
        jLabel5.setText("INFORME");
        jLabel5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel5MouseMoved(evt);
            }
        });
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelBtnInformeLayout = new javax.swing.GroupLayout(panelBtnInforme);
        panelBtnInforme.setLayout(panelBtnInformeLayout);
        panelBtnInformeLayout.setHorizontalGroup(
            panelBtnInformeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBtnInformeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelBtnInformeLayout.setVerticalGroup(
            panelBtnInformeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5)
        );

        btnCerrar.setBackground(new java.awt.Color(143, 207, 254));
        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/cerrar_1.png"))); // NOI18N
        btnCerrar.setText("Cerrar Sesion");

        javax.swing.GroupLayout jPanelBtnsLayout = new javax.swing.GroupLayout(jPanelBtns);
        jPanelBtns.setLayout(jPanelBtnsLayout);
        jPanelBtnsLayout.setHorizontalGroup(
            jPanelBtnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBtnsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBtnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JpaneRepor, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                    .addComponent(panelBtnInforme, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelBtnsLayout.setVerticalGroup(
            jPanelBtnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBtnsLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(panelBtnInforme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JpaneRepor, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 174, Short.MAX_VALUE)
                .addComponent(btnCerrar)
                .addContainerGap())
        );

        getContentPane().add(jPanelBtns, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 234, 230, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JlabReporMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JlabReporMouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
       
    }//GEN-LAST:event_JlabReporMouseClicked

    private void JlabReporMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JlabReporMouseExited
        // TODO add your handling code here:
        JpaneRepor.setBackground(new Color(14,172,209));
       
    }//GEN-LAST:event_JlabReporMouseExited

    private void JlabReporMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JlabReporMouseMoved
        // TODO add your handling code here:
        JpaneRepor.setBackground(new Color(4, 137, 177));
       
    }//GEN-LAST:event_JlabReporMouseMoved

    private void btnEnviarInformeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarInformeActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnEnviarInformeActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel5MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseMoved
        // TODO add your handling code here:
        panelBtnInforme.setBackground(new Color(4, 137, 177));
    }//GEN-LAST:event_jLabel5MouseMoved

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
        // TODO add your handling code here:
        panelBtnInforme.setBackground(new Color(14,172,209));
    }//GEN-LAST:event_jLabel5MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaMecanico1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaMecanico1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaMecanico1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaMecanico1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaMecanico1().setVisible(true);
            }
        });

        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JToggleButton BtnModoOscuro;
    private javax.swing.JLabel JlabRepor;
    public javax.swing.JPanel JpaneRepor;
    public javax.swing.JPanel PanelTabla;
    public javax.swing.JToggleButton bntSuspencion;
    public javax.swing.JButton btnCerrar;
    public javax.swing.JToggleButton btnCorona;
    public javax.swing.JToggleButton btnDireccion;
    public javax.swing.JButton btnEnviarInforme;
    public javax.swing.JButton btnListarinforme;
    public javax.swing.JToggleButton btnMotor;
    public javax.swing.JToggleButton btnTransmision;
    private javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.JComboBox<String> jComboEstado;
    public javax.swing.JComboBox<String> jComboIdBus;
    public javax.swing.JComboBox<String> jComboMotor;
    public javax.swing.JComboBox<String> jComboSuspencion;
    public javax.swing.JComboBox<String> jComboTransmision;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel11;
    public javax.swing.JPanel jPanelBtns;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    public javax.swing.JSpinner jSpinnerHoras;
    private javax.swing.JTabbedPane jTabbedPane1;
    public javax.swing.JTextArea jTextComentario;
    public javax.swing.JComboBox<String> jcomboCorona;
    public javax.swing.JComboBox<String> jcomboDireccion;
    public javax.swing.JLabel labelNombre;
    public javax.swing.JPanel panel2D;
    public javax.swing.JPanel panelBtnInforme;
    public javax.swing.JPanel panelCOrona;
    public javax.swing.JPanel panelDireccion;
    public javax.swing.JPanel panelInforme;
    public javax.swing.JPanel panelLogo;
    public javax.swing.JPanel panelMotor;
    public javax.swing.JPanel panelSuspencion;
    public javax.swing.JPanel panelTrnas;
    public javax.swing.JPanel panelUsuario;
    public javax.swing.JTable tablaInforme;
    // End of variables declaration//GEN-END:variables

    private void jTablebus() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
